### ISSUE TITLE
Cannot access heroku apps

### ISSUE THREAD

**Issue by heridotlife** [lightning-viz/lightning-python#46]
I'm using python 3.4 and here's my code:
https://github.com/retphern/hoaxbot_data_test/blob/master/lightning_scatter.py
But when i run the code, i got error like this:

> Lightning initialized
> Problem connecting to server at https://lightning-viz-veda.herokuapp.com
> status code: 401
> Traceback (most recent call last):
>   File "lightning_scatter.py", line 7, in <module>
>     lgn = Lightning(host='https://lightning-viz-veda.herokuapp.com')
>   File "/home/veda/Dev/hoaxbot_data_test/venv/lib/python3.4/site-packages/lightning/main.py", line 28, in __init__
>     raise ValueError("Could not access server")
> ValueError: Could not access server

But i can access the apps through web fine.

**Comment by heridotlife** [comment]
I found that this problem happen when using auth, when i delete the auth var from heroku its working fine.
